services:
  - type: web
    name: nfl-picks-tracker2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dash_app:server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
  - type: cron
    name: update-results
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python nfl_picks_automator.py
    schedule: "0 */2 * * 0,1,4"